require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile

Naming/AccessorMethodName:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/MutableConstant:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Enabled: false

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
